- name: configuring frontend server
  hosts: frontend
  become: true
  tasks:
    - name: install nginx
      package:
        name: nginx
        state: present
    - name: enable and start the nginx
      service:
        name: nginx
        state: started
        enabled: yes
    - name: removing the directory
      file:
        path: /usr/share/nginx/html/*
        state: absent
    - name: creating directory
      file:
        path: /usr/share/nginx/html
        state: present
    - name: downloading the code
      get_url:
        url: https://raw.githubusercontent.com/daws-90s/expense-documentation/refs/heads/main/artifacts/expense-frontend-v3.tar.gz
        dest: /tmp/frontend.tar.gz
    - name: unzipping the code
      unarchive:
        src: /tmp/frontend.tar.gz
        dest: /usr/share/nginx/html
    - name: copying expense.configure
      copy:
        src: expense.conf.j2
        dest: /etc/nginx/default.d/expense.conf
    - name: restart the nginx
      service: 
        name: nginx
        state: restarted


        